name: "ll_project"
type: "python:3.10"

relationships:
  database: "db:postgresql"

# 应用程序被暴露在网上时使用的配置
web:
  upstream:
    socket_family: unix
    commands:
      # Start指定了用哪个进程处理到来的请求
      start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
      # locations指定了到来的请求发送到什么地方
    locations:
      "/":
        passthru: true
      "/static":
        root: "static"
        expires: 1h
        allow: true

# 应用程序的永久性磁盘大小（单位为MB）
disk: 512

# 设置用于读写日志的本地挂载
mounts:
  "logs":
    source: local
    source_path: logs

# 在应用程序生命周期的不同时间点执行的钩子（hook）
hooks:
  build: |
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install -r requirements_remote.txt
    
    mkdir logs
    python manage.py collectstatic
    rm -rf logs
  deploy: |
    python manage.py migrate
